version: '3'

services:
  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    depends_on:
        - node-red
        - portainer
        - motioneye
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./reverse-proxy/headers.conf:/etc/nginx/headers.conf
    ports:
      - 80:80
    restart: always


# Node-Red
  node-red:
    #privileged: true
    image: opi-red:latest
    container_name: node-red
    #devices:
    #  - /dev/gpiomem:/dev/gpiomem
    #  - /sys/devices/platform/soc/300b000.pinctrl/gpiochip0/:/sys/devices/platform/soc/300b000.pinctrl/gpiochip0/
    volumes:
      - ./node-red-data:/data
      - /sys/class/gpio:/sys/class/gpio
      - /sys/devices/platform/soc/300b000.pinctrl/gpiochip0/:/sys/devices/platform/soc/300b000.pinctrl/gpiochip0/ 
    ports:
      - 1880:1880
    restart: always


# Portainer
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000
    restart: always


# oalprws
# 1) http://oalprws:8080/v1/identify/plate
# method POST, parametr: image (binary image to recognition)
  oalprws:
    image: dimaby/oalprws:latest
    container_name: oalprws
    ports:
      - "8080:8080"
    restart: always


# motioneye
  motioneye:
    image: ccrisan/motioneye:master-armhf
    container_name: motioneye
    ports:
      - "8081:8081"
      - "8765:8765"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./etc_motioneye:/etc/motioneye
      - ./var_lib_motioneye:/var/lib/motioneye
    restart: always
#    devices:
#      - /dev/video1:/dev/video1

#volumes:
#  reverse-proxy:
#  node-red-data:
#  portainer-data:
#  etc_motioneye:
#  var_lib_motioneye:  